-- DETOX
-- E-8 Wheel Dynamics Engine

local Wheel = {}

Wheel.VERSION = "E-8"

local WHEEL_NAMES = {
  "FL",
  "FR",
  "RL",
  "RR"
}

local DEFAULT = {
  inertia = 1.20,

  rollingResistance = 8.0,

  minimumRadius = 0.20,
  maximumRadius = 0.50
}

local function clamp(value, minValue, maxValue)
  if value < minValue then
    return minValue
  end

  if value > maxValue then
    return maxValue
  end

  return value
end

local function cross(a, b)
  return {
    x = a.y * b.z - a.z * b.y,
    y = a.z * b.x - a.x * b.z,
    z = a.x * b.y - a.y * b.x
  }
end

function Wheel.create()
  local result = {}

  for _, name in ipairs(WHEEL_NAMES) do
    result[name] = {
      inertia = DEFAULT.inertia,
      radius = 0.33,
      rollingResistance =
          DEFAULT.rollingResistance
    }
  end

  return result
end

function Wheel.updateKinematics(state)
  local body =
      state.next.body

  for _, name in ipairs(WHEEL_NAMES) do
    local wheel =
        state.next.wheels[name]

    if wheel then
      local position = {
        x = wheel.position.x or 0.0,
        y = wheel.position.y or 0.0,
        z = wheel.position.z or 0.0
      }

      local angularVelocity = {
        x = body.angularVelocity.x or 0.0,
        y = body.angularVelocity.y or 0.0,
        z = body.angularVelocity.z or 0.0
      }

      local rotationalVelocity =
          cross(
            angularVelocity,
            position
          )

      wheel.contactVelocity.x =
          body.velocity.x
          + rotationalVelocity.x

      wheel.contactVelocity.y =
          body.velocity.y
          + rotationalVelocity.y

      wheel.contactVelocity.z =
          body.velocity.z
          + rotationalVelocity.z

      wheel.longitudinalVelocity =
          wheel.contactVelocity.x

      wheel.lateralVelocity =
          wheel.contactVelocity.y
    end
  end
end

function Wheel.updateSlip(state)
  for _, name in ipairs(WHEEL_NAMES) do
    local wheel =
        state.next.wheels[name]

    if wheel then
      local referenceVelocity =
          wheel.longitudinalVelocity or 0.0

      local wheelVelocity =
          wheel.omega *
          math.max(wheel.radius, 0.001)

      local denominator =
          math.max(
            math.abs(referenceVelocity),
            1.0
          )

      wheel.slipRatio =
          (
            wheelVelocity
            - referenceVelocity
          )
          / denominator

      local lateralVelocity =
          wheel.lateralVelocity or 0.0

      wheel.slipAngle =
          math.atan(
            lateralVelocity /
            denominator
          )
    end
  end
end

function Wheel.update(state)
  local dt =
      state.next.vehicle.dt or
      (1.0 / 333.0)

  if dt <= 0 then
    dt = 1.0 / 333.0
  end

  for _, name in ipairs(WHEEL_NAMES) do
    local wheel =
        state.next.wheels[name]

    if wheel then
      local radius =
          clamp(
            wheel.radius or 0.33,
            DEFAULT.minimumRadius,
            DEFAULT.maximumRadius
          )

      local inertia =
          DEFAULT.inertia

      local drive =
          wheel.torque.drive or 0.0

      local brake =
          wheel.torque.brake or 0.0

      local tire =
          wheel.torque.tire or 0.0

      local rolling =
          wheel.torque.loss or 0.0

      local brakeSign = 0.0

      if wheel.omega > 0.001 then
        brakeSign = 1.0
      elseif wheel.omega < -0.001 then
        brakeSign = -1.0
      end

      local netTorque =
          drive
          - brake * brakeSign
          + tire
          - rolling * brakeSign

      local angularAcceleration =
          netTorque / inertia

      wheel.angularAcceleration =
          angularAcceleration

      wheel.omega =
          wheel.omega
          + angularAcceleration * dt

      wheel.rotation =
          wheel.rotation
          + wheel.omega * dt

      wheel.valid = true

      -- Reaction torque generated by the tire
      -- is preserved for the drivetrain solver.
      wheel.torque.tire =
          -(
            wheel.force.longitudinal or 0.0
          )
          * radius
    end
  end

  return true
end

return Wheel
